#cloud-config

users: 
   - name: anand
     passwd: <REPLACE____WTIH____PWD>
     ssh_authorized_keys:
        - ssh-rsa <REPLACE________WITH______ACTUAL_____PVT____KEY>
     groups: 
       - sudo
       - docker

hostname: "CoreOS-XX"
coreos:
  etcd2:
    name: coreOS-XX
    # This is a single node cluster
    discovery: https://discovery.etcd.io/ace281800fbc4f9afe92cc2f8fc5ebab   
    advertise-client-urls: http://$private_ip4:2379
    initial-advertise-peer-urls: http://$private_ipv4:2380
    listen-client-urls: http://0.0.0.0:2379
    initial_cluster: coreOS-XX=http://$private_ipv4:2380
    listen-peer-urls: http://$private_ipv4:2380
  fleet:
    public-ip: $private_ipv4
  flannel:
    interface: $private_ipv4
  units:
   - name: etcd-member.service
     command: start
   - name: etcd.service
     mask: true
   - name: flanneld.service
     drop-ins:
       - name: 50-network-config.conf
         content: |
           [Service]
           ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{ "Network": "10.1.0.0/16" }'
     
   - name: docker.service
     enable: true
     drop-ins:
        - name: 60-docker-wait-for-flannel-config.conf
          content: |
            [Unit]
            After=flanneld.service
            Requires=flanneld.service

            [Service]
            Restart=always
          
   - name: docker-tcp.socket
     enable: true
     content: |
       [Unit]
       Description=Docker Socket for the API

       [Socket]
       ListenStream=2375
       Service=docker.service
       BindIPv6Only=both

       [Install]
       WantedBy=sockets.target